# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it

    - uses: actions/checkout@v2
      
    - name: Build the stack
      run: docker-compose up -d
              
    - uses: DamianReeves/write-file-action@v1.0
      with:
        path: .coveralls.yml
        contents: |
          service_name: github-action
          repo_token: ${{ secrets.COVERALLS_TOKEN }}
        write-mode:   overwrite

    - uses: DamianReeves/write-file-action@v1.0
      with:
        path: .env
        contents: |
          PORT=3000
          DATABASE_CONNECTION_NAME=dev
          JWTSECRET=asdfasdasdfasdff  
          JWT_EXPIRATION_TIME=1h
          SMTP_URL=localhost
          SMTP_PORT=1025
          SMTP_USERNAME=prueba@prueba.com
          SMTP_PASSWORD=prueba
          TEST_TIMEOUT=5000
        write-mode:   overwrite
      
    - uses: DamianReeves/write-file-action@v1.0
      with:
        path: ormconfig.json
        contents: |
          [{
           "name": "dev",
           "type": "postgres",
           "host": "localhost",
           "port": 5432,
           "username": "test",
           "password": "test",
           "database": "test",
           "synchronize": true,
           "dropSchema": true,
           "logging": false,
           "entities": [
              "src/entities/**/*.ts"
           ],
           "migrations": [
              "src/migration/**/*.ts"
           ],
           "subscribers": [
              "src/subscriber/**/*.ts"
           ],
           "cli": {
              "entitiesDir": "src/entities",
              "migrationsDir": "src/migration",
              "subscribersDir": "src/subscriber"
           }
          }]
        write-mode:   overwrite

    - uses: actions/setup-node@v2-beta
      with:
        node-version: '10.19.0'

    - run: npm install
    
    - run: cat ormconfig.json
    
    - run: ./node_modules/.bin/fake-smtp-server  -a prueba@prueba.com:prueba &
    
    - name: run app
      run: npm run coveralls
